name: Upload iOS Release

on:
  workflow_dispatch:  # Manueller Start über GitHub UI

jobs:
  upload:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Generate App Icons
      run: dart run flutter_launcher_icons
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        cd ..
    
    - name: Build iOS Release
      run: |
        flutter build ios --release
        
    - name: Create IPA Archive
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r MorenaYoga-Release.ipa Payload
        rm -rf Payload
    
    - name: Upload Release IPA
      uses: actions/upload-artifact@v4
      with:
        name: morena-yoga-ios-release
        path: MorenaYoga-Release.ipa
        retention-days: 90
